name: Build Docs

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install poetry
      run:  |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -o get-poetry.py
        python get-poetry.py --preview -y
        source $HOME/.poetry/env
        poetry config virtualenvs.in-project true
    - name: Install all dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
    - name: Build Docs
      run: |
        source $HOME/.poetry/env
        poetry run mkdocs build
    - name: Add Custom Domain Settings
      run: |
        echo "pythainav.nutchanon.org" >> ./site/CNAME
    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
