name: Tests

on: [push, pull_request]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6.9, 3.7.5, 3.8.0]
    steps:
    - uses: actions/checkout@master
    - name: Install poetry
      run:  |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -y
        source $HOME/.poetry/env
        poetry config virtualenvs.in-project true
        - name: Set up cache
    - uses: actions/cache@v1
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install
    - name: Test
      run: |
        source $HOME/.poetry/env
        poetry run pytest tests
